! blocked permute routine (generated by Gemini pro)

subroutine permute_12_3d(A, B, n1, n2, n3)
  ! permutes first and second dims of A, writing into B
  implicit none
  ! Dimensions: A(n1, n2, n3), B(n2, n1, n3)
  integer, intent(in) :: n1, n2, n3
  double precision, intent(in)  :: A(n1, n2, n3)
  double precision, intent(out) :: B(n2, n1, n3)

  integer :: i, j, k, ii, jj
  integer, parameter :: block_size = 32

  !$OMP PARALLEL DO PRIVATE(k, ii, jj, i, j) SHARED(A, B, n1, n2, n3) IF(n3 > 100)
  do k = 1, n3
     ! Tiled loops for the first two dimensions to optimize cache usage
     do jj = 1, n2, block_size
        do ii = 1, n1, block_size

           ! Internal block processing
           do j = jj, min(jj + block_size - 1, n2)
              do i = ii, min(ii + block_size - 1, n1)
                 B(j, i, k) = A(i, j, k)
              end do
           end do

        end do
     end do
  end do
  !$OMP END PARALLEL DO
  
end subroutine permute_12_3d

subroutine transpose(A, B, n1, n2)
  ! transpose A, writing into B
  implicit none
  ! Dimensions: A(n1, n2), B(n2, n1)
  integer, intent(in) :: n1, n2
  double precision, intent(in)  :: A(n1, n2)
  double precision, intent(out) :: B(n2, n1)

  integer :: i, j, k, ii, jj
  integer, parameter :: block_size = 32
  
  ! Tiled loops for the first two dimensions to optimize cache usage
  do jj = 1, n2, block_size
     do ii = 1, n1, block_size

        ! Internal block processing
        do j = jj, min(jj + block_size - 1, n2)
           do i = ii, min(ii + block_size - 1, n1)
              B(j, i) = A(i, j)
           end do
        end do

     end do
  end do

end subroutine transpose
